### ISSUE TITLE
Hard to read github project description

### ISSUE THREAD

**Issue by Flowtter** [tanguymaraux/portfolio#3]
I've notice that reading the description of your github project is impossible while hovering.
A quick-fix would be to add some opacity on the image and darken the main color.

https://github.com/tanguymaraux/portfolio/blob/6d939927f8e6ed8b2906b3f17babb831ac7fbe28/src/components/GithubProject/githubproject.scss#L100-L106

```scss
.project:hover {
    background-color: darken(rgb(233, 233, 233), 20%);

    a>.githubgimg_project {
        opacity: 0.3;
    }

}
```
